#########################
## Sample Sass Lint File
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # Set the formatter to 'html'
  formatter: html
  # Output file instead of logging results
  output-file: 'linters/sass-lint.html'
  # Raise an error if more than 50 warnings are generated
  max-warnings: 50
# File Options
files:
  include: 'src/**/*.scss'
# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 2
  mixin-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: snakecase
  no-debug: 1
  no-duplicate-properties:
    - 2
    -
      exclude:
        - background
        - background-image
  no-ids: 0 # necessary for Gaia profiles
  no-important: 0 # necessary for Gaia profiles
  no-warn: 1
  hex-notation: # using default lowercase notation
    - 2
  trailing-semicolon: 1
  indentation:
    - 2
    -
      size: 2
  property-sort-order:
    - 1
    -
      ignore-custom-properties: true
  variable-for-property:
    - 0
  variable-name-format:
    - 1
    -
      allow-leading-underscore: false
